name: Docker Image CI

on:
  push:
    tags: '**'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      -
        name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: jeffersonlab/hallc-hcana

      -
        name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}"
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            DOCKER_TAG=${{ steps.meta.outputs.tags }}
            APP_VERSION=${{ github.ref_name}}
            REPO_NAME=${{ github.event.repository.name }}